# Generated by Django 5.1.2 on 2024-12-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
