version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DATABASES_NAME}
      POSTGRES_USER: ${DATABASES_USER}
      POSTGRES_PASSWORD: ${DATABASES_PASSWORD}
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    restart: always

  celery:
    build: .
    command: celery -A habits_project worker -l INFO
    depends_on:
      - redis
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always

  celery_beat:
    build: .
    command: celery -A habits_project beat -l INFO
    depends_on:
      - redis
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always

volumes:
  db_data:
